# Basic conda environment for running TESCA
name: tesca
channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - geopandas
  - configargparse
  - fiona
  - pyyaml
  - openjdk
  - joblib
  - jpype1
  - numpy
  - pandas
  - psutil
  - requests
  - shapely
  - numpydoc
  - flask
  - flask-wtf
  - flask-executor
  - pip:
    - gtfs-lite
    - pygris
    - r5py==0.1.0