# This is a configuration file for a TESCA analysis
# The parameters provided in this file can be changed
#
analyst: Willem  # The analysis name appears on the reporting output
project: Morning Peak and Evening Service Comparisons  # The project title is used for plot titles
description: Comparing weekday peak and weekend service in Chicago.  # Longer title for reporting outputs
location: Philadelphia Metropolitan Statisical Area
# TODO: Allow scenario-specific infinity values, or use an infinity factor
fetch_demographics: true  # Whether or not to fetch demographics
infinity_value: 180  # You can restrict the maximum walking time
max_time_walking: 30  # We now define the opportunities as they are coded in the opportunities file
uid: chicago-test # A unique ID which is used for logging (should match the cache folder)
verbosity: DEBUG # A flag to set the verbosity of the output
opportunities:  # Each item in the list of opportunities corresponds with a column in opportunities.csv
  emp_all:
    method: cumulative  # Method can be either "cumulative" or "travel_time"
    name: Total Employment
    parameters:  # Cumulative parameters are travel time thresholds, travel_time parameters are nth closest
    - 30
    - 45
  emp_low:
    method: cumulative
    name: Low-Income Employment
    parameters:
    - 30
    - 45
  hospitals:
    method: travel_time
    name: Hospitals
    parameters:
    - 1
  pharmacies:
    method: travel_time
    name: Pharmacies
    parameters:
    - 1
    - 3
  urgent_care_facilities:
    method: travel_time
    name: Urgent Care
    parameters:
    - 1
# Demographics are defined here
demographics:  # Each key correponds with a column in the demogrpahics.csv file and is given a name
  B03002_003E: White People
  B03002_004E: Black People
  B03002_006E: AAPI
  B03002_012E: Hispanic or Latino
# Scenarios are defined as an ordered list
scenarios:
- duration: 120  # Duration of analysis, in minutes
  name: Morning Peak  # A pretty name for the analysis
  start_datetime: 2023-03-07 07:00  # Should be in YYYY-MM-DD HH:MM
  transit_modes:  # A list of transit modes to use, in capitalized string form
  - TRANSIT
- duration: 120
  name: Evening
  start_datetime: 2023-03-07 21:00
  transit_modes:
  - TRANSIT
